Feature/35 lazy images
ostatni5/tk-2022 pull request #50
Opened 2022-04-10 11:07 UTC by ostatni5

close #35 
![obraz](https://user-images.githubusercontent.com/26521377/162615114-d2899d99-d650-401c-8e0e-b0cdad00250c.png)

2022-04-10 11:49 UTC, retkiewi submitted a review, later dismissed
lgtm

2022-04-10 11:49 UTC, retkiewi commented on ui/src/lib/ImageFinder.svelte
> +                    gender: 'female',
Can we remove image gender?

2022-04-10 12:04 UTC, michal367 requested changes

2022-04-10 12:04 UTC, michal367 commented on ui/src/lib/ImageFinder.svelte
> +<script lang="ts">
this ImageFinder.svelte is completely different from this what is on main.
On main is new version of file in lib/components

2022-04-11 14:11 UTC, michal367 approved these changes

2022-04-11 14:24 UTC, merged