Feature/40 text component UI
ostatni5/tk-2022 pull request #52
Opened 2022-04-11 20:34 UTC by Derstilon

![image](https://user-images.githubusercontent.com/26445545/162827260-60595782-4dcd-4d65-aafb-6709260e1223.png)
Closes #40

2022-04-11 20:54 UTC, retkiewi requested changes

2022-04-11 20:54 UTC, retkiewi commented on ui/src/lib/components/Form.svelte
> +            Tetadata <i class="arrow {arrowDirection}" />
The f**k is Tetadata

2022-04-11 20:54 UTC, retkiewi commented on ui/src/lib/components/Form.svelte
> +                {#if formData["text"].hasText}
make the fields render as disabled instead of hiding them

2022-04-12 08:25 UTC, Derstilon commented on ui/src/lib/components/Form.svelte
> +                <label
![image](https://user-images.githubusercontent.com/26445545/162915928-cceaadda-8ca8-4c26-8f64-cfb32f44e26a.png)

2022-04-12 09:00 UTC, retkiewi commented on ui/src/lib/components/Form.svelte
> +                <label
niech będzie xd

2022-04-12 09:01 UTC, retkiewi approved these changes

2022-04-12 10:48 UTC, merged