Feature/56 weather server component
ostatni5/tk-2022 pull request #65
Opened 2022-05-07 20:21 UTC by Derstilon

Closes #56

2022-05-08 11:05 UTC, retkiewi commented
Add this node to the "start" scripts.

2022-05-08 12:12 UTC, retkiewi requested changes

2022-05-09 08:47 UTC, Derstilon commented on weather_server/main.py
> +		"""Get weather"""
done. Can be checked here:
https://github.com/ostatni5/tk-2022/blob/8aa56c03cc7c9d79a77e5b7f73ff1869dd6979b5/weather_server/weather_module.py#L31

2022-05-09 10:06 UTC, retkiewi requested changes
Almost there :)

2022-05-09 10:06 UTC, retkiewi commented on weather_server/weather_module.py
> +		chunk_size = len(paths) // THREAD_LIMIT + (1 if len(paths) % THREAD_LIMIT != 0 else 0)
The chunking and filtering should probably be separate functions.

2022-05-09 10:06 UTC, retkiewi commented on weather_server/__main__.py
> +	create_app().run(host='localhost', port=8086)
Wrong indent.

2022-05-09 10:06 UTC, retkiewi commented on weather_server/check_json.py
> +for line in weather_types_file:
Use list comprehensions -> LABELS = [<list comprehension>]

2022-05-09 10:06 UTC, retkiewi commented on weather_server/create_app.py
> +	app = Flask(__name__)
wrong indent

2022-05-09 10:06 UTC, retkiewi commented on weather_server/test/test_module.py
> +        os.path.join(ROOT_PATH,"resources/Cloudy/Cloudy13.jpg"),
Indent formatting

2022-05-09 10:06 UTC, retkiewi commented on weather_server/weather_module.py
> +from marshmallow import Schema, fields
This file has different indents than the rest.

2022-05-09 15:04 UTC, retkiewi commented on weather_server/check_json.py
> +	return error
Guess whats missing (spoiler it should be at the end of the file)

2022-05-09 15:04 UTC, retkiewi commented on weather_server/create_app.py
> +	app = Flask(__name__)
The indent is still wrong btw

2022-05-09 15:04 UTC, retkiewi commented on weather_server/test/test_module.py
> +        # app.run()
.

2022-05-09 15:04 UTC, retkiewi commented on weather_server/weather_module.py
> +from marshmallow import Schema, fields
.

2022-05-09 15:04 UTC, retkiewi commented on weather_server/weather_module.py
> +		chunk_size = len(paths) // THREAD_LIMIT + (1 if len(paths) % THREAD_LIMIT != 0 else 0)
.

2022-05-09 15:45 UTC, retkiewi approved these changes
Looks good :)

<img src="https://media3.giphy.com/media/c5skRQb3BXp8RwKGKW/giphy.gif"/>

2022-05-09 17:16 UTC, retkiewi approved these changes

2022-05-09 17:20 UTC, merged